### ISSUE TITLE
Autobuilds with releases

### ISSUE THREAD

**Issue by iBobik** [AudMonkey/AudMonkey#18]
Build releases by GH Actions.

**Comment by IshoAntar** [comment]
Currently I've integrated [travis-ci](https://travis-ci.com/) for CI/CD
which supports uploading artifacts to GitHub see [dpl v1 docs](https://docs.travis-ci.com/user/deployment/releases/) and [dpl v2 docs](https://docs.travis-ci.com/user/deployment-v2)
not sure which one i should use to be honest (?), i guess we go with the latest?

But it's not setup as of yet. Since after the changes
in #10 i'm not sure if it will even run properly (it does "on my machine" though).

I guess we could release an alpha build for testing, to see if any regressions
have occurred because of the changes?

I'll see what i can do with travis, regarding releases.

**Comment by iBobik** [comment]
I never used Travis.
