### ISSUE TITLE
Can't seem to open/import old style aup pachages on 1.o.1 appimage

### ISSUE THREAD

**Issue by catlover1019** [AudMonkey/AudMonkey#89]
**Describe the bug**
I try to open any aup project and i get an error like so:
"Couldn't import the project:

Could not load file: [name].aup""

**To Reproduce**
1. try to open an aup project

**Expected behavior**

**Additional information (please complete the following information):**
 - OS: Ubuntu 21.04

**Comment by IshoAntar** [comment]
I can confirm this, saving a project with Audacity 2.4.1 (latest on Arch)
and trying to open it in AudMonkey (even latest `devel`)
results in an error dialog with the given message.

I'll look into this as soon as possible.

**Comment by IshoAntar** [comment]
Alright, a quick test an i was able to "make it work" (read, workaround),
this is caused by the rename spree i went into when i made the fork,

for now you can get it to work by opening the `aup` file in a text editor,
look for the `audacityversion` property in the `project` tag (should be right at the beginning). i.e. what it looks like:
```
<project ... audacityversion="<some_version_number>" ... >
```

Just rename it to `audmonkeyversion` at it should import it.
